# Generated by Django 5.2.7 on 2026-02-11 12:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caleb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price_currency',
            field=models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=10),
        ),
    ]
