# Generated by Django 5.2.7 on 2026-02-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caleb', '0003_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
