# Generated by Django 5.2.7 on 2026-02-14 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caleb', '0004_bankaccount_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('NGN', 'Naira'), ('USD', 'Dollar'), ('GBP', 'Pounds')], max_length=10)),
                ('how_did_you_hear', models.CharField(choices=[('social-media', 'Social Media'), ('friend', 'Friend'), ('advertisement', 'Advertisement')], max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caleb.bankaccount')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caleb.ticket')),
            ],
        ),
    ]
