# Generated by Django 5.2.7 on 2026-02-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caleb', '0005_ticketpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='payment_reference',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
